mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
#from mysite.views import hello, current_datetime, hours_ahead, contact
#from books import views
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello/$', views.hello),
    url(r'^time/$', views.current_datetime),
    url(r'^time/plus/(\d{1,2})/$', views.hours_ahead),
    url(r'^search_form/$', views.search_form),
    url(r'^search/$', views.search),
    url(r'^contact/$', contact),
    url(r'^reviews/2003/$', views.special_case_2003),
    url(r'^reviews/([0-9]{4})/$', views.year_archive),
    url(r'^reviews/([0-9]{4})/([0-9]{2})/$', views.month_archive),
    url(r'^reviews/([0-9]{4})/([0-9]{2})/([0-9]+)/$', views.review_detail),
]

if settings.DEBUG:
    urlpatterns += [url(r'^debuginfo/$', views.debug),]

books/models.py
from django.db import models

# Create your models here.

class Publisher(models.Model):
	"""docstring for Publisher"""
	name = models.CharField(max_length=30)
	address = models.CharField(max_length=50)
	city = models.CharField(max_length=60)
	state_province = models.CharField(max_length=30)
	country = models.CharField(max_length=50)
	website = models.URLField()
	def __str__(self):
		return self.name
	class Meta:
		ordering = ['name']

class Author(models.Model):
	#salutation = models.CharField(max_length=10)
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email = models.EmailField(blank=True, verbose_name='e-mail')
	#headshot = models.ImageField(upload_to='author_headshots')
	def __str__(self):
		return u'%s %s' % (self.first_name, self.last_name)

class BookManger(models.Manager):
	def title_count(self, keyword):
		return self.filter(title__icontains=keyword).count()

#定义Manger子类
class DahlBookManger(models.Manager):
	def get_queryset(self):
		return super(DahlBookManger, self).get_queryset().filter(author='Roald Dahl')

#添加Manager子类到Book模型
class Book(models.Model):
	title = models.CharField(max_length=100)
	authors = models.ManyToManyField(Author)
	publisher = models.ForeignKey(Publisher)
	publication_date = models.DateField(blank=True, null=True)
	#num_pages = models.IntergerField(blank=True, null=True)
	#objects = BookManger()
	objects = models.Manager()#默认管理器
	dahl_objects = DahlBookManger()#专门查询Dahl的管理器
	def __str__(self):
		return self.title

mysite/forms.py
from django import forms


class ContactForm(forms.Form):
	subject = forms.CharField(max_length=100)
	email = forms.EmailField(required=False, label='Your e-mail adress')
	message = forms.CharField(widget=forms.Textarea)
	def clean_message(self):
		message = self.cleaned_data['message']
		num_words = len(message.split())
		if num_words < 4:
			raise forms.ValidationError("Not enough words!")
		return message

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from books.models import Book


# Create your views here.
def search_form(request):
	return render(request, 'search_form.html')

'''
#第一版
def search(request):
	if 'q' in request.GET:
		message = 'You searched for: %r' % request.GET['q']
	else:
		message = 'You submitted an empty form.'
	return HttpResponse(message)
'''
'''
#第二版
def search(request):
	if 'q' in request.GET and request.GET['q']:
		q = request.GET['q']
		books = Book.objects.filter(title__icontains=q)
		return render(request, 'search_requests.html', {'books': books, 'query': q})
	else:
		#return HttpResponse('Please submit a search term.')
		return render(request, 'search_form.html', {'error': True})
'''
def search(request):
	#error = False
	errors = []
	if 'q' in request.GET:
		q = request.GET['q']
		if not q:
			#error = True
			errors.append('Enter a search term.')
		elif len(q) > 20:
			errors.append('Please enter at most 20  characters.')
		else:
			books = Book.objects.filter(title__icontains=q)
			return render(request, 'search_requests.html', {'books': books, 'query': q})
	return render(request, 'search_form.html', {'errors': errors})

mysite/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import get_template
from django.shortcuts import render
from django.core.mail import send_mail
from mysite.forms import ContactForm
import datetime
#from django.template import Context


def hello(request):
	return HttpResponse("1")

def current_datetime(request):
	now = datetime.datetime.now()
	'''
	t = get_template('current_datetime.html')
	#html = "It is now %s" % now
	html = t.render({'current_date': now})
	return HttpResponse(html)
	'''
	return render(request, 'current_datetime.html', {'current_date': now})#改版v1.0

def hours_ahead(request, offset):
	try:
		offset = int(offset)
	except ValueError:
		raise Http404()
	t = get_template('Future_hours.html')
	dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
	#html = "In %s hour(s), it will be %s" % (offset, dt)
	html = t.render({'hour_offset': offset, 'next_time': dt})
	return HttpResponse(html)
	#return HttpResponse(request, 'Future_hours.html', {'hour_offset': offset, 'next_time': dt}) 

def display_meta(request):
	values = request.META.items()
	values.sort()
	html = []
	for k, v in values:
		html.appened('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
	return HttpResponse('<table>%s</table>' % '\n'.join(html))

def contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			send_mail(
				cd['subject'],
				cd['message'],
				cd.get('email', 'noreply@example.com'),
				['siteowner@example.com']
				)
			return HttpResponseRedirect('/contact/thanks')
	else:
		form = ContactForm(
			initial = {'subject': 'My site'}
			)
	return render(request, 'contact_form.html', {'form': form})

books/templates/search_form.html
<!DOCTYPE html>
<html>
<head>
	<title>Search</title>
</head>
<body>
	{% if errors %}
		<ul>
			{% for error in errors %}
				<li>{{ error }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	<form action="" method="get">
		<input type="text" name="q">
		<input type="submit" name="Search">
	</form>
</body>
</html>

books/templates/search_requests.html
<!DOCTYPE html>
<html>
	<head>
		<title>Book Search</title>
	</head>
	<body>
		<p>You searched for: <strong>{{query}}</strong></p>
		{% if books %}
			<p>Found {{ books|length }} book{{ books|pluralize }}.</p>
			<ul>
				{% for book in books %}
				<li>{{ book.title }}</li>
				{% endfor %}
			</ul>
		{% else %}
			<p>No books matched your search criteria.</p>
		{% endif %}
	</body>
</html>

templates/Future_hours.html
{% extends "base.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
{% endblock %}

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">

<html>
<head>
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<h1>My helpful timestamp site.</h1>
	{% block content %}{% endblock %}

	{% block footer %}
	<hr>
	<p>Thanks for visiting my site.</p>
	{% endblock %}
</body>
</html>

templates/contact_form.html
<style type="text/css">
	ul.errorlist{
		margin: 0;
		padding: 0;
	}
	.errorlist li{
		background-color: red;
		color: white;
		display: block;
		font-size: 10px;
		margin: 0 0 3px;
		padding: 4px 5px;
	}
</style>


<!DOCTYPE html>
<html>
<head>
	<title>Contact us</title>
</head>
<body>
	<h1>Contact us</h1>
	{% if form.errors %}
		<p style="color: red">
			Please correct the error {{ form.errors|pluralize }} below.
		</p>
	{% endif %}
	<form action="" method="post">
		<div class="field">
			{{ form.subject.errors }}
			<label for="id subject">Subject:</label>
			{{ form.subject }}
		</div>
		<div class="field">
			{{ form.email.errors }}
			<label for="id_email">Your e-mail address:</label>
			{{ form.email }}
		</div>
		<div class="field {% if form.message.errors %}errors{% endif %}">
			{% if form.message.errors %}
			<ul>
				{% for error in form.message.errors %}
					<li><strong>{{ error }}</strong></li>
				{% endfor %}
			</ul>
			{% endif %}
			<label for="id_message">Message:</label>
			{{ form.message }}
		</div>
		{% csrf_token %}
		<input type="submit" name="Submit">
	</form>
</body>
</html>

templates/current_datetime.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">

{% extends "base.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
	<p>It is now {{ current_date }}</p>
{% endblock %}